# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Raul Dipeas"
description: > # this means to ignore newlines until "email:"
   Acompanhe minhas postagens

email: rauldipeas@disroot.org
#blog logo
logo: "https://rauldipeas.com.br/assets/images/avatar.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "https://rauldipeas.com.br/assets/images/backgrounds/street-1.gif"

name: 'Raul Dipeas'
author: 'Raul Dipeas'
author_image: "https://rauldipeas.com.br/assets/images/avatar.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon: twitter
#    url: https://twitter.com/rauldipeas
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon: facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/rauldipeas
    desc:	Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - icon:	mastodon
    url:	https://mastodon.social/@raul_dipeas
    desc:	Follow me on Mastodon
    share_url:
    share_title:
    share_link:

#  - icon: google-plus
#    url: https://google.com/???
#    desc: Add me on google+
#    share_url:
#    share_title:
#    share_link:
