name: Implantação
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalação do Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Compilação do Jekyll
        run: bundle exec jekyll build -s blog -d site/blog
        env:
          JEKYLL_ENV: production
      - name: Envio para o GitHub Pages
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'site'
          destination_repo: 'rauldipeas/rauldipeas.github.io'
          destination_folder: '/'
          destination_branch: 'gh-pages'
          user_email: 'github.rauldipeas@lock.email'
          user_name: 'rauldipeas'
          commit_message: '^site'
      - name: Envio para o Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=rauldipeas --commit-dirty=true
          quiet: true
      - name: Envio para o Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rauldipeas.surge.sh'
          project: 'site'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          remove-cancelled: true
          remove-failed: true
          remove-obsolete: true
          token: ${{ secrets.PAT }}
          #remove-older-than: 7d
