
name: Snake
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10,22 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Atualizar contribuições
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rauldipeas
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9    
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
