name: Implantação no Surge
on:
  push:
    branches:    
      - 'main'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: |
          git clone https://github.com/rauldipeas/blog
          cd blog
          bundle
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          ls -l ../
          #mv _site ../public/blog
        env:
          JEKYLL_ENV: production
      - uses: actions/checkout@v3
      - name: Upload para o Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rauldipeas.surge.sh'
          project: 'public'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Limpeza de logs antigos
        run: bash actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}