name: Implementação no Surge
on:
  push:
    branches:    
      - 'main'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload para o Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rauldipeas.surge.sh'
          project: 'public'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Limpeza de logs antigos
        run: bash actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}